### ISSUE TITLE
Facing issue with specific_message_bytes_to_row function

### ISSUE THREAD

**Issue by sidtandon2014** [aroch/protobuf-dataframe#1]
I have modified the code like this

def specific_message_bytes_to_row(pb_bytes):
    # import your protobuf here
    msg = SMSBuffer.FromString(pb_bytes)
    row = message_to_row(SMSBuffer.DESCRIPTOR, msg)
    return row

schema = schema_for(SMSBuffer().DESCRIPTOR)

specific_message_bytes_to_row_udf = udf(specific_message_bytes_to_row,schema)

but its throwing error while creating event column
df = df.withColumn("event", specific_message_bytes_to_row_udf(col("value")))

**Error:**
**File "/databricks/spark/python/pyspark/cloudpickle.py", line 635, in save_global
    return Pickler.save_global(self, obj, name=name)
  File "/usr/lib/python3.7/pickle.py", line 957, in save_global
    (obj, module_name, name)) from None
_pickle.PicklingError: Can't pickle <class 'google.protobuf.pyext._message.CMessage'>: it's not found as google.protobuf.pyext._message.CMessage**

**Comment by aroch** [comment]
There's the commented line: `# import your protobuf here`
Instead of this line put your import statement (e.g. `from foo.bar import SMSBuffer`)
You need to place the import statement inside the function rather than on the top of your file, to avoid Serialization  of the Protobuf message (which is not serializable).
This is what I believe is causing this error.
Please let me know if this works for you.
